bluebutton-data-pipeline-fhir-load/pom.xml, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/load/FhirBundleResult.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/load/FhirLoader.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformer.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/FhirLoaderIT.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/load/FhirLoaderTest.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformerTest.java, bluebutton-data-pipeline-fhir-load/src/test/resources/logback-test.xml, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/RifFilesProcessor.java, bluebutton-data-pipeline-sampledata/src/main/java/gov/hhs/cms/bluebutton/datapipeline/sampledata/StaticRifResourceGroup.java
Covers the following issues:
* [CBBD-84: RIF data loading into FHIR](http://issues.hhsdevcloud.us/browse/CBBD-84)
* [CBBD-100: Transformed RIF FHIR IDs and references are mostly invalid](http://issues.hhsdevcloud.us/browse/CBBD-100)
This pull request will span Sprint 3 and 4.
=> RIF Loading into FHIR (initial version)

bluebutton-data-pipeline-fhir-load/pom.xml, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformer.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformerTest.java
Fix [CBBD-103: DataTransformer needs to use RIF version 5](http://issues.hhsdevcloud.us/browse/CBBD-103).
=> DataTransformer needs to use RIF version 5

Jenkinsfile, bluebutton-data-pipeline-fhir-load/pom.xml, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/FhirLoaderIT.java
Per [CBBD-40: Update ITs to automatically deploy "clean" FHIR servers](http://issues.hhsdevcloud.us/browse/CBBD-40).
=> Update ITs to automatically deploy "clean" FHIR servers

bluebutton-data-pipeline-sampledata/src/main/resources/rif-static-samples/sample-c.tar.bz2
@karlmdavis This just contains the compressed sample file from Scott. Please merge if you don't have any concerns. (cc @skoerselman )
=> Add rif-1mil-sample file

bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformerTest.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/RifFilesProcessor.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/RifFilesProcessorTest.java, bluebutton-data-pipeline-rif/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/model/CarrierClaimGroup.java, bluebutton-data-pipeline-rif/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/model/PartDEventRow.java
@karlmdavis @sbrockhoff   Please review when you get a chance.  I removed all of the .ordinal() coding from the other resources.  Thanks.
=> CBBD-89 developed code for Carrier RIF parsing

Jenkinsfile, bluebutton-data-pipeline-rif-extract/pom.xml, dev/devenv-readme.md
http://issues.hhsdevcloud.us/browse/CBBD-114
This is the build side of this. There's also a build *server* pull request, too.
=> CBBD-114: Add AWS API credentials to Jenkins, for ITs that need to work with S3

bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformer.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformerTest.java
@sbrockhoff @karlmdavis Ignore my first request as I pushed my changes to the wrong branch..ugh.  Please review when you get a chance.   Difficult piece of mapping from CCW to FHIR in my opinion is when you can't find a FHIR resource element to map to. You can create extensions for data at any time but should this be done for all "non mappable" fields as this can lead to more complexity and overhead in the FHIR resources that we don't need. I just created extensions for those data elements that I thought will be useful to have. Thanks.
=> Carrier transform

bluebutton-data-pipeline-rif/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/model/InpatientClaimGroup.java
@karlmdavis   Fix for JavaDoc in InpatientClaimGroup
=> CBBD-112 Fix JavaDoc error

bluebutton-data-pipeline-rif-extract/pom.xml, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorWorker.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetTestUtilities.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorIT.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorWorkerIT.java
Intended to resolve http://issues.hhsdevcloud.us/browse/CBBD-132.
=> CBBD-132: Amazon's S3 API is only eventually consistent for DELETEs, which is causing intermittent test failures

.gitattributes
Not 100% sure that this will work, but at first blush, it seems like the right solution.
=> CBBD-142: Trying to resolve Windows vs. Linux line ending problems

bluebutton-data-pipeline-benchmarks/src/test/ansible/roles/server_etl/templates/bluebutton-data-pipeline-app.sh.j2, bluebutton-data-pipeline-fhir-load/pom.xml, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/LoadableFhirBundle.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/SharedDataFhirBundle.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/SharedDataManager.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/load/FhirBundleResult.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/load/FhirLoader.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/load/FhirTestUtilities.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformer.java, bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/TransformedBundle.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/FhirLoaderIT.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/SharedDataManagerIT.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformerTest.java, pom.xml
http://issues.hhsdevcloud.us/browse/CBBD-147
=> CBBD-147: Update data-pipeline to be compatible with STU3 FHIR server

pom.xml
http://issues.hhsdevcloud.us/browse/CBBD-153
(See my commit message for details.)
=> CBBD-153: Intermittent (and weird!) HAPI error: InternalErrorException: Failed to call access method

bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorWorker.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/S3RifFile.java
http://issues.hhsdevcloud.us/browse/CBBD-143
=> CBBD-143: Copy S3 objects to local temp files before processing data sets.

bluebutton-data-pipeline-fhir-load/src/main/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformer.java, bluebutton-data-pipeline-fhir-load/src/test/java/gov/hhs/cms/bluebutton/datapipeline/fhir/transform/DataTransformerTest.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/RifFilesProcessor.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/RifFilesProcessorTest.java, bluebutton-data-pipeline-rif/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/model/DMEClaimGroup.java
http://issues.hhsdevcloud.us/browse/CBBD-282
Going to have to merge this prior to review, but a post-merge review would still be appreciated.
=> Marked the DME.providerNPI field as Optional

bluebutton-data-pipeline-benchmarks/src/test/java/gov/hhs/cms/bluebutton/datapipeline/benchmarks/S3ToDatabaseLoadAppBenchmark.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetManifest.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorWorker.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetQueue.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetTestUtilities.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/S3RifFile.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/task/DataSetMoveTask.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/task/ManifestEntryDownloadTask.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetManifestTest.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorIT.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorWorkerIT.java
http://issues.hhsdevcloud.us/browse/CBBD-298
=> CBBD-298: Store DataSetManifest timestamps as a String to avoid Instant's precision loss issues

bluebutton-data-pipeline-app/src/main/resources/logback.xml
http://issues.hhsdevcloud.us/browse/CBBD-303
=> CBBD-303: Increased Flyway logging.

bluebutton-data-pipeline-rif-load/src/test/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoaderIT.java
It'd gotten a bit unwieldy with the delta tests that were added. I think it's now a bit easier to understand.
https://issues.hhsdevcloud.us/browse/CBBD-367
=> CBBD-367: Cleaned up RifLoaderIT some

bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetTestUtilities.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/LocalRifFile.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/subset/DataSetSubsetter.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/synthetic/SyntheticDataFixer.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/synthetic/SyntheticDataUploader.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/synthetic/package-info.java, bluebutton-data-pipeline-rif-load/src/main/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/BlockingThreadPoolExecutor.java, bluebutton-data-pipeline-rif-load/src/main/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoader.java, bluebutton-data-pipeline-rif-load/src/main/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoaderTestUtils.java, bluebutton-data-pipeline-rif-load/src/test/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoaderIT.java
Please see the commit comments for details on what's been done here and why.
https://issues.hhsdevcloud.us/browse/CBBI-299
=> CBBI-299: Synthetic data and bug fixes

bluebutton-data-pipeline-rif-load/src/test/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoaderIT.java
It'll fail otherwise.
CBBI-229
=> Ensure that this test is skipped when low mem

bluebutton-data-pipeline-app/src/test/java/gov/hhs/cms/bluebutton/datapipeline/app/S3ToDatabaseLoadAppIT.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitor.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorWorker.java
Was making the log files painfully unusable: useless entries logged every second.
https://issues.hhsdevcloud.us/browse/CBBD-315
=> CBBD-315: Reduced log noise from S3 scanning

bluebutton-data-pipeline-rif-load/src/main/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/LoadAppOptions.java
Oops: had just forgotten it, previously.
https://jira.cms.gov/browse/BLUEBUTTON-467
=> BLUEBUTTON-467: Added idempotency to LoadAppOptions.toString()

bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetMonitorWorker.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/DataSetQueue.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/S3RifFile.java, bluebutton-data-pipeline-rif-extract/src/main/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/task/S3TaskManager.java, bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/s3/task/ManifestEntryDownloadTaskIT.java
Trying to resolve some intermittent timeouts being seen when loading the 60M random benes data set in TEST.
Trying a couple of things:
1. Download fewer files ahead and in parallel.
2. Trying to resolve intermittent S3 download timeouts that are being seen in the TEST environment on large files.
https://jira.cms.gov/browse/BLUEBUTTON-467
=> BLUEBUTTON-467: Resolve intermittent S3 download timeouts

bluebutton-data-pipeline-rif-load/src/main/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoaderTestUtils.java
This will hopefully (if we're real lucky) reduce memory pressure in our tests.
BLUEBUTTON-637
=> BLUEBUTTON-637: Ensure that JPA sessions are closed.

bluebutton-data-pipeline-rif-load/src/main/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoader.java
Needed to add the check for the BeneficiariesHistoryTemp table for the one-time load of the historical HICN's in RifLoader; thus the code will hash the HICN's and store the unhashed hicn into the field hichUnhashed for this one-time load table.
=> Bluebutton-916: hash HICN--one-time load into BeneficiariesHistoryTemp

bluebutton-data-pipeline-rif-load/src/test/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoaderIT.java
Has some pre-reqs; the build will fail until these are merged:
* https://github.com/CMSgov/bluebutton-data-model/pull/57
* and maybe this one: https://github.com/CMSgov/bluebutton-data-model/pull/58
https://jira.cms.gov/browse/BLUEBUTTON-972
=> BLUEBUTTON-972: Added an IT for SAMPLE_MCT

bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/RifFilesProcessorTest.java
Fixing a broken test case.
BLUEBUTTON-1010
=> BLUEBUTTON-1010: Fix test case to account for earlier column change

bluebutton-data-pipeline-rif-load/src/test/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoaderIT.java
https://jira.cms.gov/browse/MCT-2159
=> MCT-2159: Verify that the new MCT updates load

bluebutton-data-pipeline-rif-extract/src/test/java/gov/hhs/cms/bluebutton/datapipeline/rif/extract/RifFilesProcessorTest.java, bluebutton-data-pipeline-rif-load/src/test/java/gov/hhs/cms/bluebutton/data/pipeline/rif/load/RifLoaderIT.java
Adding an additional assert to make sure beneHistory records have the
correct beneficiaryId
=> BLUEBUTTON-865: Add HICN/MBI to Patient Resource
